# Generated by Django 4.2.2 on 2024-12-20 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0002_students_delete_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Employee',
        ),
    ]
