# Generated by Django 4.2.2 on 2024-12-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0004_intern_delete_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='job',
            field=models.CharField(choices=[('job', 'job'), ('intern', 'intern')], default='intern', max_length=50),
        ),
    ]
