# Generated by Django 4.2.2 on 2024-12-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0005_alter_intern_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='myfile',
            field=models.FileField(default=True, upload_to='file'),
        ),
    ]
