# Generated by Django 4.2.2 on 2024-12-24 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0006_intern_myfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intern',
            old_name='experience',
            new_name='college',
        ),
        migrations.RemoveField(
            model_name='intern',
            name='qualification',
        ),
    ]
