# Generated by Django 4.2.2 on 2024-12-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0007_rename_experience_intern_college_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='myfile',
            field=models.FileField(default='intern/file/file.txt', upload_to='file'),
        ),
    ]
