# Generated by Django 4.2.2 on 2024-12-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0008_alter_intern_myfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='myfile',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='file/'),
        ),
    ]
